config/routes.rb
Rails.application.routes.draw do
  resources :imported_files
    resources :contacts do
    collection { post :upload }
  end

  resources :invalid_contacts do
    collection { post :upload }
  end

  devise_for :users
  get "home/index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

# Contact class
class Contact < ApplicationRecord
  belongs_to :user

  NAME_VALIDATION = /\A[a-zA-Z -]+\z/.freeze
  EMAIL_VALIDATION = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  DATE_FORMAT = /\A\d{4}-\d{2}-\d{2}\z/.freeze

  validates :name, presence: true, format: { with: NAME_VALIDATION }
  validates :email, presence: true, uniqueness: true, format: { with: EMAIL_VALIDATION }
  validates :date_of_birth, presence: true, format: { with: DATE_FORMAT || "%F" }
  validates :phone, presence: true
  validates :address, presence: true
  validates :credit_card, presence: true
  validates :franchise, presence: true

  before_save :downcase_email

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/models/imported_file.rb
# frozen_string_literal: true

# Imported files class
class ImportedFile < ApplicationRecord
  include AASM

  belongs_to :user

  aasm do
    state :on_hold, initial: true
    state :processing, :finished, :failed

    event :process do
      transitions from: :on_hold, to: :processing
    end

    event :fail do
      transitions from: :processing, to: :failed
    end

    event :complete do
      transitions from: :processing, to: :finished
    end
  end
end

app/models/invalid_contact.rb
# frozen_string_literal: true

# Invalid contact class
class InvalidContact < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

# User class created by devise
class User < ApplicationRecord
  attr_writer :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contacts
  has_many :invalid_contacts
  has_many :imported_files

  validate :validate_username
  validates_format_of :username, with: /^[a-zA-Z0-9_.]*$/, multiline: true
  validates :username, presence: true, uniqueness: { case_sensitive: false }

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value
                                    OR lower(email) = :value",
                                    { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    return error.add(:username, :invalid) if User.where(email: username).exists?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[username email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: %i[login password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

# Contacts controller class
class ContactsController < ApplicationController
  def index
    @user = current_user
    @contacts = @user.contacts.order(:sort).paginate(page: params[:page], per_page: 20)
  end

  def create
    @contact = @user.contacts.new(contact_params)
  end

  def upload
    @user = current_user
    UploadCsv.new(@user, params[:file]).upload

    redirect_to contacts_path, notice: "Contacts Added Successfully"
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :phone, :address, :credit_card)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Controller class
class HomeController < ApplicationController
  def index; end
end

app/controllers/imported_files_controller.rb
# frozen_string_literal: true

class ImportedFilesController < ApplicationController
  def index
    @user = current_user
    @imported_files = @user.imported_files
  end

  def create
    @imported_files = @user.imported_files.new(imported_file_params)
  end

  private

  def imported_file_params
    params.require(:imported_file).permit(:file, :name, :aasm_state)
  end
end

app/controllers/invalid_contacts_controller.rb
# frozen_string_literal: true

# InvalidContactsController class
class InvalidContactsController < ApplicationController
  def index
    @user = current_user
    @invalid_contacts = @user.invalid_contacts.paginate(page: params[:page], per_page: 20)
  end

  def create
    @invalid_contact = @user.invalid_contacts.new(invalid_contact_params)
  end

  def upload
    UploadCsv.new(current_user, params[:file]).upload

    redirect_to invalid_contacts_path, notice: "Invalid Contacts Added Successfully"
  end

  private

  def invalid_contact_params
    params.require(:invalid_contact).permit(:name, :email, :phone, :address, :credit_card)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/imported_files_helper.rb
# frozen_string_literal: true

module ImportedFilesHelper
end

app/helpers/invalid_contacts_helper.rb
# frozen_string_literal: true

module InvalidContactsHelper
end

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/index.html.erb
<div class="container">
  <div class="media-body">
    <h1>Contacts List</h1>
    <table class="table table-hover">
      <thead>
      <tr>
        <th> Name </th>
        <th> Phone </th>
        <th> Email </th>
        <th> Date of Birth </th>
        <th> Address </th>
        <th> Credit card number </th>
        <th> Franchise </th>
      </tr>
      </thead>
      <tbody>

      <% @user.contacts.each do |contact| %>
        <tr>
          <td><%= contact.name.upcase %></td> </td>
          <td><%= contact.phone %> </td>
          <td><%= contact.email %> </td>
          <td><%= contact.date_of_birth %> </td>
          <td><%= contact.address %> </td>
          <td><%= contact.credit_card %> </td>
          <td><%= contact.franchise.upcase %> </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div>
      <%= will_paginate @contacts %>
    </div>
  </div>

  <div class="container">
    <h3> Upload CSV File </h3>
    <%= form_tag upload_contacts_path, multipart: true do |f| %>
      <%= file_field_tag :file %>
      <%= submit_tag "Upload" %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="container center">
<h1> Welcome <%= current_user.username.capitalize if user_signed_in? %> </h1>
  <p> <%= link_to "Log in to continue", new_user_session_path unless user_signed_in?%> </p>
</div>

app/views/imported_files/index.html.erb
<div class="container">
  <div class="media-body">
    <h1>Imported Files</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>File name </th>
          <th>Aasm state</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @imported_files.each do |file| %>
          <tr>
            <td><%= file.name %></td>
            <td><%= file.aasm_state %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/invalid_contacts/index.html.erb
<div class="container">
  <div class="media-body">
    <h1>Rejected contacts</h1>
    <table class="table table-hover">
      <thead>
      <tr>
        <th> Name </th>
        <th> Phone </th>
        <th> Email </th>
        <th> Date of Birth </th>
        <th> Address </th>
        <th> Credit card number </th>
        <th> Franchise </th>
        <th> Error message </th>
      </tr>
      </thead>
      <tbody>

      <% @user.invalid_contacts.each do |contact| %>
        <tr>
          <td><%= contact.name.upcase %></td> </td>
          <td><%= contact.phone %> </td>
          <td><%= contact.email %> </td>
          <td><%= contact.date_of_birth %> </td>
          <td><%= contact.address %> </td>
          <td><%= contact.credit_card %> </td>
          <td><%= contact.franchise.upcase if contact.franchise.present? %> </td>
          <td><%= contact.message %> </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div>
      <%= will_paginate @invalid_contacts %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Contact importer" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Contact importer" %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'partials/navigation' %>
    </header>
    <main role="main">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</html>

app/views/layouts/devise.html.erb
<% content_for :content do %>
  <div class="container">
    <div class="col-lg-6 align-center">
      <p>
        <%= yield %>
      </p>
    </div>
  </div>
<% end %>
<%= render template: "layouts/application" %>

app/views/partials/_navigation.html.erb
<nav class="navbar navbar-dark navbar-static-top navbar-expand-md">
  <div class="container">
    <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">Toggle navigation</span>
    </button> <%= link_to "Contact importer", root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav mr-auto">
        <li class="nav-item"><%= link_to "Home", home_index_path, class: "nav-link" %></li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Contacts", contacts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Invalid contacts", invalid_contacts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Imported files", imported_files_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <% if current_user.username %>
            <li class="nav-item">
              <%= link_to current_user.username, edit_user_registration_path, class: "nav-link" %>
            </li>
          <%else%>
            <li class="nav-item">
              <%= link_to current_user.email, edit_user_registration_path, class: "nav-link" %>
            </li>
          <%end%>
        <%else%>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create account", new_user_registration_path, class: "nav-link" %>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>